export const ORDER_LIST_REQ = "ORDER_LIST_REQ";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAIL_REQ = "ORDER_DETAIL_REQ";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const ORDER_DELETE_REQ = "ORDER_DELETE_REQ";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";

export const ORDER_APPROVE_REQ = "ORDER_APPROVE_REQ";
export const ORDER_APPROVE_SUCCESS = "ORDER_APPROVE_SUCCESS";
export const ORDER_APPROVE_FAIL = "ORDER_APPROVE_FAIL";