export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ"   
export const PRODUCT_LIST_REQ_FAIL = "PRODUCT_LIST_REQ_FAIL"
export const PRODUCT_LIST_REQ_SUCCESS = "PRODUCT_LIST_REQ_SUCCESS"

export const PRODUCT_DETAIL_REQ = "PRODUCT_DETAIL_REQ"   
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_DETAIL_REQ_FAIL"
export const PRODUCT_DETAIL_REQ_SUCCESS = "PRODUCT_DETAIL_REQ_SUCCESS"

export const PRODUCT_DELETE_REQ = "PRODUCT_DELETE_REQ";
export const PRODUCT_DELETE_REQ_SUCCESS = "PRODUCT_DELETE_REQ_SUCCESS";
export const PRODUCT_DELETE_REQ_FAIL = "PRODUCT_DELETE_REQ_FAIL";

export const DECREASE_PRODUCT_QUANTITY_SUCCESS = "DECREASE_PRODUCT_QUANTITY_SUCCESS";
export const DECREASE_PRODUCT_QUANTITY_FAIL = "DECREASE_PRODUCT_QUANTITY_FAIL";
export const DECREASE_PRODUCT_QUANTITY_REQUEST = "DECREASE_PRODUCT_QUANTITY_REQUEST";

export const PRODUCT_DETAIL_RESET = 'PRODUCT_DETAIL_RESET';