export const USER_LOGIN_REQ = "USER_LOGIN_REQ"
export const USER_LOGIN_REQ_SUCCESS = "USER_LOGIN_REQ_SUCCESS"
export const USER_LOGIN_REQ_FAIL = "USER_LOGIN_REQ_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQ = "USER_REGISTER_REQ"
export const USER_REGISTER_REQ_SUCCESS = "USER_REGISTER_REQ_SUCCESS"
export const USER_REGISTER_REQ_FAIL = "USER_REGISTER_REQ_FAIL"

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_ADMIN_TOGGLE_REQUEST = "USER_ADMIN_TOGGLE_REQUEST";
export const USER_ADMIN_TOGGLE_SUCCESS = "USER_ADMIN_TOGGLE_SUCCESS";
export const USER_ADMIN_TOGGLE_FAIL = "USER_ADMIN_TOGGLE_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";
export const USER_LOGIN_CLEAR_ERROR = 'USER_LOGIN_CLEAR_ERROR';
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";
export const USER_PROFILE_ERROR_CLEAR = 'USER_PROFILE_ERROR_CLEAR';

export const PASSWORD_RESET_CODE_REQUEST = 'PASSWORD_RESET_CODE_REQUEST';
export const PASSWORD_RESET_CODE_SUCCESS = 'PASSWORD_RESET_CODE_SUCCESS';
export const PASSWORD_RESET_CODE_FAIL = 'PASSWORD_RESET_CODE_FAIL';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL';

export const CHECK_EMAIL_REQ = 'CHECK_EMAIL_REQ';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';

export const SEND_VERIFICATION_CODE_REQUEST = 'SEND_VERIFICATION_CODE_REQUEST';
export const SEND_VERIFICATION_CODE_SUCCESS = 'SEND_VERIFICATION_CODE_SUCCESS';
export const SEND_VERIFICATION_CODE_FAIL = 'SEND_VERIFICATION_CODE_FAIL';

export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAIL = 'VERIFY_CODE_FAIL';